##  Polynomial  Regression
 Polynomial regression is an advancement to regular linear regression. Linear regression, accounts for the relationship between the independent variables and the dependent variable provided the the relationship is linear. 
      However, Polynomial regression sees to account for linear and non-linear relationships.
### Concepts in Polynomial regression 
  * Polynomial degree: This is the polynomial term with the highest power.
  * Polynomial term: this is the combination of a coefficient, variable and power.
  * Over_Fitting: A situation where the model learns the noise in the data, rather than the underlying pattern. 
  * Under_fitting: A situation where the model is too simple and as a result, fails to capture the underlying pattern of the data. 

In [ ]:
y = 2x*3x 

In [4]:
#import the necessarylibraries
import pandas as pd
import numpy as np
data = pd.read_csv('multiple_linear_regression_dataset.csv')

In [5]:
data.head(1)

age  experience  income
0   25           1   30450

### Polynomial uses the regular linear model's OLS (Ordinary Least Squares)

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
#assign our variables
x = data[['age','experience']]
y = data['income']

In [8]:
#create a polynomial resgression of two degree
poly = PolynomialFeatures(2, include_bias = True)
x_poly = poly.fit_transform(x)

In [9]:
#check the look of our independent variables after the polnomial transformation
x_poly[0]

array([  1.,  25.,   1., 625.,  25.,   1.])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
#perform train test split to our data
x_train,x_test,y_train,y_test = train_test_split(x_poly,y, random_state = 42, train_size = 0.7 )

In [12]:
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

#### fiting our models

In [13]:
modelSK = LinearRegression()
modelSK.fit(x_train,y_train)

LinearRegression()

In [22]:
modelSM = sm.OLS(y_train,x_train)
modelSM = modelSM.fit()

In [15]:
r2 = modelSK.score(x_train,y_train)
r2

0.9831118290973656

##### Make predictions

In [16]:
y_pred = modelSK.predict(x_test)
y_pred

array([31909.67301466, 32951.19021231, 39162.13365369, 34807.3120157 ,
       37537.93620321, 41383.7767291 ])

### Merics for model analysis
* R2
* MSE (Mean Squared Error: it is used to  evaluate the performance of a regression model
* rsme: squared root of MSE

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mse = mean_squared_error(y_test,y_pred)

In [19]:
rsme = np.sqrt(mse)

In [20]:
print(f' R2 {r2},\n MSE {mse},\n RSME {rsme}')

 R2 0.9831118290973656,
 MSE 2448476.4262033547,
 RSME 1564.7608207657024


In [23]:
modelSM.summary()

C:\Users\PRESHMIRA\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_axis_nan_policy.py:418: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=14 observations were given.
  return hypotest_fun_in(*args, **kwds)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 income   R-squared:                       0.983
Model:                            OLS   Adj. R-squared:                  0.973
Method:                 Least Squares   F-statistic:                     93.14
Date:                Wed, 20 Nov 2024   Prob (F-statistic):           7.19e-07
Time:                        15:24:16   Log-Likelihood:                -118.36
No. Observations:                  14   AIC:                             248.7
Df Residuals:                       8   BIC:                             252.5
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const           5e+04   1.15e+04      4.353      0.002    2.35e+04    7.65e+04
x1         -1180.1249    655.480     -1.800      0.109   -2691.664     331.414
x2          3046.3453    868.458      3.508      0.008    1043.678    5049.013
x3            14.1122      8.753      1.612      0.146      -6.073      34.298
x4           -18.0215     27.887     -0.646      0.536     -82.328      46.285
x5            -0.4868     45.415     -0.011      0.992    -105.214     104.240
==============================================================================
Omnibus:                        1.148   Durbin-Watson:                   2.431
Prob(Omnibus):                  0.563   Jarque-Bera (JB):                0.943
Skew:                          -0.437   Prob(JB):                        0.624
Kurtosis:                       2.076   Cond. No.                     5.78e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.78e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### Handling over fitting using regularizations
Regularization is the penalizing of features with high coefficients, drawing coefficients that are too high to values near zero, thereby reducing models sensitivity
* Ridge (L2 regularization): is a technique used to prevent overfitting in machine learning models, particularly in linear regression and other models that involve optimization. It works by adding a penalty to the loss function, specifically a term proportional to the square of the coefficients (weights) of the model.
* Lasso (L1 regularization): is another type of regularization technique used in regression models, specifically to prevent overfitting and improve model generalization. Lasso applies L1 regularization, which differs from Ridge regularization (L2 regularization) by adding a penalty based on the absolute values of the coefficients rather than their squared values.

In [25]:
#import the regularization libraries
from sklearn.linear_model import Ridge,Lasso

In [42]:
ridgemodel = Ridge(alpha = 2)
ridgemodel = ridgemodel.fit(x_train,y_train)
ridgemodel

Ridge(alpha=2)

In [43]:
ridgemodel.coef_.round(),modelSK.coef_.round()

(array([   0., -413., 1740.,    3.,   17.,  -24.]),
 array([    0., -1180.,  3046.,    14.,   -18.,    -0.]))

#### using Lasso(L2 regularization)

In [58]:
lassomodel = Lasso(alpha = 4)
lassomodel = lassomodel.fit(x_train,y_train)
lassomodel

C:\Users\PRESHMIRA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.047e+06, tolerance: 1.069e+05
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=4)

In [59]:
lassomodel.coef_.round(-1),modelSK.coef_.round()

(array([    0., -1120.,  2980.,    10.,   -20.,    -0.]),
 array([    0., -1180.,  3046.,    14.,   -18.,    -0.]))

In [61]:
data.describe(include = 'all')

age  experience        income
count  20.000000   20.000000     20.000000
mean   39.650000    6.200000  40735.500000
std    10.027725    4.124382   8439.797625
min    23.000000    1.000000  27840.000000
25%    31.500000    3.750000  35452.500000
50%    40.000000    5.000000  40190.000000
75%    47.000000    9.000000  45390.000000
max    58.000000   17.000000  63600.000000

In [62]:
data

age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700